### ISSUE TITLE
Short github urls

### ISSUE THREAD

**Issue by tpecholt** [TheLartians/CPM#52]
It should be possible to use short github identifiers instead of full url as in cget. For example instead of 

https://github.com/jgm/cmark

Just write
jgm/cmark

**Comment by TheLartians** [comment]
I think we could add some shortcuts to popular hosting sites, so that

```
  GIT_REPOSITORY https://github.com/catchorg/Catch2.git
```

could be shortened to

```
  GITHUB_REPOSITORY catchorg/Catch2
```

Besides `GITHUB_REPOSITORY`, we should also add `GITLAB_REPOSITORY` for diversity.
