### ISSUE TITLE
Automatic versioning convention detection

### ISSUE THREAD

**Issue by TheLartians** [TheLartians/CPM#54]
Currently `GIT_TAG` defaults to `v(VERSION)`, which is the versioning convention many Git projects use, but not all. Is there a portable and efficient way to detect or find git-tag based versioning schemes?

**Comment by DeveloperPaul123** [comment]
What is the goal here? Do you intend to allow users of CPM to be able to just specify a version number without having to explicitly match the version tag naming scheme? (i.e. `v1.0.0` versus `1.0.0`)?

**Comment by TheLartians** [comment]
Exactly, currently the version identifier must be specified twice, if the tag naming scheme differs from the default. It would be great if this code duplication could be avoided.
Come to think of it, it might actually make more sense to extract the version identifier from the tag (if not explicitly specified) and not the other way around.🤔

**Comment by DeveloperPaul123** [comment]
Right, I think that does make sense. Do you intend to support versions that don't use semantic versioning?

**Comment by TheLartians** [comment]
I'm planning to support anything that can be easily detected and converted to [CMake's `VERSION_LESS` versioning](https://cmake.org/cmake/help/v3.0/command/if.html) with a regex.
What are common non-semantic versionings?

**Comment by DeveloperPaul123** [comment]
I've seen many things....I think semantic versioning is pretty ubiquitous but I've also seen variants of it (appending some sort of hash or something `1.0.0-21fw2ef9` or `1.0.0-a1` and so on). Some project may also use build numbers instead of an actual version. There are also versions with the form `1.3.2.11002`.

**Comment by TheLartians** [comment]
So CMake's  `VERSION_LESS` ignores everything after the first non-numeric or dot characters. So e.g. `1.0.0-21fw2ef9` and `1.0.0-a1` will be treated as the same version. CPM will then use added the first variant without emitting a warning. This should be fine as the top project can use this to specify the exact version if needed.

**Comment by DeveloperPaul123** [comment]
Sounds good to me, that seems like a reasonable assumption to make 👍
