### ISSUE TITLE
Is it possible to use CPM to include boost

### ISSUE THREAD

**Issue by luketrevorrow** [TheLartians/CPM#69]
Hi, is it possible to use CPM to include and build Boost, or do packages need to follow good CMake practices? Can you use something like:

CPMAddPackage(
  NAME boost
  GITHUB_REPOSITORY boostorg/boost
  VERSION 1.70.0
  GIT_TAG boost-1.70.0
)

if (boost_ADDED)
  add_library(boost INTERFACE IMPORTED)
  target_include_directories(boost INTERFACE "${boost_SOURCE_DIR}/include")
endif()

target_link_libraries(asio-test PRIVATE boost)

**Comment by TheLartians** [comment]
Yes, that will indeed get you all boost libraries that [don't require building](https://stackoverflow.com/a/50776718/2397086). For boost libraries that require building (such as boost asio) you will need to configure the build manually in CMake.

Note that the include path must be the boost source directory and that downloading the released archive is much faster than cloning the entire boost git repositories.

```cmake
CPMAddPackage(
  NAME boost
  VERSION 1.70.0
  URL https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.tar.gz
  URL_HASH SHA256=882b48708d211a5f48e60b0124cf5863c1534cd544ecd0664bb534a4b5d506e9
)

if (boost_ADDED)
  add_library(boost INTERFACE IMPORTED)
  target_include_directories(boost INTERFACE "${boost_SOURCE_DIR}")
endif()
```

**Comment by TheLartians** [comment]
FYI I've found a [project](https://github.com/Orphis/boost-cmake) attempting to port boost to CMake. This makes it easy to add boost and build the required components for asio.

```cmake
CPMAddPackage(
  NAME boost
  GITHUB_REPOSITORY Orphis/boost-cmake
  VERSION 1.67.0
)

target_link_libraries(asio-test Boost::system)
```

**Comment by luketrevorrow** [comment]
Thanks so much for the quick reply! I will go and test it all now.

**Comment by andersfylling** [comment]
I'm struggling to get the boost filesystem working right.

``` 

CPMAddPackage(
  NAME tabulate
  GITHUB_REPOSITORY p-ranav/tabulate
  GIT_TAG origin/master # this holds boost 1.70?
)

set(Boost_USE_STATIC_LIBS ON)
target_link_libraries(Sortnet PUBLIC boost Boost::system)
```

error message:

`CMake Error: install(EXPORT "SortnetTargets" ...) includes target "Sortnet" which requires target "Boost_system" that is not in any export set.`

My project is [here](https://github.com/andersfylling/sorting-nine-inputs-requires-twenty-five-comparisons)

Is there a project right now that is able to do this?

**Comment by TheLartians** [comment]
Hm once I have some time I can check in detail, but from the sound of it it seems that CMake is complaining about Boost not creating an installable target. This would lead `packageProject()` to fail. Can you configure the project if you erase the `packageProject` command?

**Comment by TheLartians** [comment]
And if that fails maybe you could avoid boost by using `std::filesystem` which is part of C++17.

**Comment by andersfylling** [comment]
Yeah, my dependency is fairly light, so for me its not much of an issue to switch. 

I tried deleting the build folders but that suddenly started stating that Boost already existed in my _dep folder after trying to rebuild it. I decided to swap it out with std::filesystem. But I wasn't able to figure out the error message im afraid.
