### ISSUE TITLE
How to make a project CPM-ready?

### ISSUE THREAD

**Issue by aggsol** [TheLartians/CPM#72]
I understand the usage but documentation is missing on how to make my projects useable with CPM:

- Where to store the version number?
- Where to place public include headers?
- How to create header only projects?
- How to define static or dynamic libs?

**Comment by TheLartians** [comment]
Hello aggsol, thanks for your feedback! You are right, some information on project best-practices would be useful in the documentation.

CPM differs from conventional package managers as it does not require any additional work on the project maintainers end. All information about the project (such as version number, origin etc.) is provided by the users as shown in the examples.
This means that all decisions such as header location and linking are left to the project implementers. To make the usage of your library as convenient as possible (with or without CPM), I recommend to use CMake and follow [modern CMake practices](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right). E.g. not mess with global configuration variables and for a header-only library, you should create an interface target. 
As for versioning, it should be made clear to your users what the current project's version is. I would recommend using [semantic versioning](https://en.wikipedia.org/wiki/Software_versioning) and GitHub's [release feature](https://help.github.com/en/articles/creating-releases) for marking new releases. That way GitHub automatically creates tags in your repository that can be used to refer to a specific version.

**Comment by aggsol** [comment]
Thank you for the fast answer. I am not using GitHub for my projects. I assume when the tag and the version in the CMake file are identical like

```
project("myproj" VERSION 0.1.0.0 LANGUAGES CXX)
```
and the tag is named `0.1.0.0` that is enough then?

**Comment by TheLartians** [comment]
Yes, the tag alone would be enough though, but it is a good practice to also add the version to your CMake script.
The `v` prefix is a GitHub convention and the default git tag when none is explicitly specified. You can use any other git tag by specifying the optional `GIT_TAG` argument.

**Comment by aggsol** [comment]
You could open up the wiki and we can put information and examples there. Also a list of projects actively advocating the usage of CPM.

**Comment by TheLartians** [comment]
Thats a great idea! I don't have time to write docs atm but I've opened up the wiki as a first step.
