### ISSUE TITLE
GitLab repo is not cloneable

### ISSUE THREAD

**Issue by aggsol** [TheLartians/CPM#75]
I get the following error:
```
-- CPM: adding package CliArguments@0 (v0)
[ 11%] Performing download step (git clone) for 'cliarguments-populate'
fatal: could not create work tree dir '': No such file or directory
fatal: could not create work tree dir '': No such file or directory
fatal: could not create work tree dir '': No such file or directory
-- Had to git clone more than once:
          3 times.
CMake Error at cliarguments-subbuild/cliarguments-populate-prefix/tmp/cliarguments-populate-gitclone.cmake:66 (message):
  Failed to clone repository:
  'https://gitlab.com/aggsol/cliarguments-cpp.git'

```
I add the package like this:

```cmake
CPMAddPackage(
  NAME CliArguments
  GIT_REPOSITORY https://gitlab.com/aggsol/cliarguments-cpp.git
  TAG 1.0.0
)
```
The tag has been created as you can see here: https://gitlab.com/aggsol/cliarguments-cpp/-/tags

Did I miss something else to setup?

**Comment by TheLartians** [comment]
Hey aggsol, `TAG` is not a valid parameter for providing a git tag, can you try using `GIT_TAG` instead? 
For all available options and their definitions, see the [ExternalProject documentation](https://cmake.org/cmake/help/v3.11/module/ExternalProject.html#external-project-definition).

**Comment by aggsol** [comment]
Yes, that was it! ty!
