### ISSUE TITLE
Setting CPM_SOURCE_ROOT from the environment

### ISSUE THREAD

**Issue by aggsol** [TheLartians/CPM#82]
I use similar dependencies for various project, so that new feature would help me a lot. Is there a way to setup an environment variable for it? I would set `CPM_SOURCE_ROOT` per machine/user not per project. I would point in to `$HOME/.cache/CPM` or similar

**Comment by TheLartians** [comment]
It should be possible to read in an environmental environment and set the value, if it exists. However I believe sharing downloads could easily break if different projects use different versions (/sources/download commands) of the same dependency. We should should this first before endorsing a global download location. Perhaps it's possible to safely encode the version/source information in the download path?
Also note that only the download itself and not the build can be cached, as builds would break when different options or generators are used. For faster builds I recommend checking out caching compiler wrappers such as [sccache](https://github.com/mozilla/sccache).

**Comment by aggsol** [comment]
I use ccache already. It is more about caching the downloads, the version should be in then path name then. If everything is found in the cache then no online connection would be required. I wonder if this is out of scope for CPM. So the cache contains all downloads like this named by CPM params already required?

```
.cache/CPM/{NAME}-{URL}-{VERSION}
```

**Comment by TheLartians** [comment]
I've [implemented](https://raw.githubusercontent.com/TheLartians/CPM/source-dir-env/cmake/CPM.cmake) the above suggestion. CPM should now check for the environmental variable `CPM_SOURCE_ROOT` which should point to an absolute path to the download directory.
@aggsol It would be great if you could check if that works your projects and solves your use-case.

**Comment by TheLartians** [comment]
I've just did a simple test and it seems that CMake actually removes the source directories before trying to repopulate them. I'll investigate if we can change this behaviour.

**Comment by aggsol** [comment]
@TheLartians I will give it a go, please gimme some days. Currently busy T_T

**Comment by TheLartians** [comment]
Thanks! NP, I just want to make sure it’s battle tested before publishing as this seems to be a big feature.

**Comment by aggsol** [comment]
I tested it in two different systems with environment variable and as command line parameter. Different builds and different versions of libraries. I used `$HOME/.cache/CPM` for both and checked creation of folders and files. This works really good! Maybe the var should be renamed `CPM_SOURCE_CACHE` then?

**Comment by TheLartians** [comment]
Awesome, thanks!
I've also been testing this for the last days and it works quite well. Some small issues occurred when updating dependencies or clearing the cache, but those should be resolved by now.
I agree, we should rename the var to `CPM_SOURCE_CACHE`.
